DIRS = $(sort $(dir $(wildcard */)))
LIST = $(DIRS:/=)

TESTS=$(wildcard *.c) $(wildcard *.cpp) $(DIRS)
TESTS_OBJ=$(patsubst %.c, %.log, $(TESTS)) \
					$(patsubst %.cpp, %.log, $(TESTS))

.PHONY: check
check: $(TESTS_OBJ)

.PHONY: $(TESTS)
%.log: %.c
	@python3 ../lib/runtest.py $^ -o $@

%.log: %.cpp
	@python3 ../lib/runtest.py $^ -o $@

$(DIRS):
	$(MAKE) -C $@

clean:
	rm -f *.log *.ipa-clones *.out
	for folder in $(DIRS); do $(MAKE) -C $$folder clean; done;
